---
title: "Raster Benchmark"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r message=FALSE}
library(ggplot2)
```

```{r collapse=TRUE}
cat(paste("R", getRversion(), "\n"))
cat(paste("sf", packageVersion("sf"), "\n"))
cat(paste("stars", packageVersion("stars"), "\n"))
cat(paste("terra", packageVersion("terra"), "\n"))
cat(paste("raster", packageVersion("raster"), "\n"))
cat(paste("raster", packageVersion("data.table"), "\n"))
cat(paste("exactextractr", packageVersion("exactextractr"), "\n"))
```

```{r collapse=TRUE}
# check it manually
cat("Python 3.8.5", "\n")
cat("rasterio 1.2.2", "\n")
cat("rasterstats 0.15.0", "\n")
cat("rioxarray 0.3.1")
```

```{r}
files = list.files("results", full.names = TRUE)
df = lapply(files, read.csv2)
df = do.call(rbind, lapply(files, read.csv2,
                           colClasses = c("factor", "factor", "numeric")))
```

## Extract values by points
#### 68 275 points

```{r extract-points}
df_agg = df[df$task == "extract-points", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Downsample
#### 30 to 90 m

```{r downsample}
df_agg = df[df$task == "downsample", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Calculate NDVI

```{r ndvi}
df_agg = df[df$task == "ndvi", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.4) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.4) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Write multilayer
#### 10 layers with masks, LZW compression

```{r write}
df_agg = df[df$task == "write", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Crop
#### by rectangular extent

```{r crop}
df_agg = df[df$task == "crop", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

## Zonal statistics
#### mean values for 1 940 buffers

```{r zonal}
df_agg = df[df$task == "zonal", ]
df_agg = merge(aggregate(time ~ package, df_agg, median),
               aggregate(time ~ package, df_agg, sd), by = "package")
colnames(df_agg)[2:3] = c("median", "sd")

ggplot(df_agg, aes(x = reorder(package, -median), y = median)) + 
  geom_col(width = 0.3) +
  geom_errorbar(aes(ymin = median, ymax = median + sd),
                color = "red", width = 0.3) +
  ylab("Time [s]") +
  xlab("Package") +
  coord_flip() +
  theme_light()
```

```{r final-plot, eval=FALSE}
df_agg = aggregate(time ~ task + package, df, median)
python = c("rasterio", "rasterstats", "rioxarray")
df_agg$lang = ifelse(df_agg$package %in% python, "Python", "R")
df_agg$lang = as.factor(df_agg$lang)

# drop slower funs from same packages 
pkg_drop = c("raster-fun", "stars-st_apply", "terra-fun")
df_agg = df_agg[!df_agg$package %in% pkg_drop, ]

pkg_name = strsplit(as.character(df_agg$package), "-")
df_agg$package = sapply(pkg_name, "[[", 1)

xlabels = c("Crop", "Downsample", "Extract", "NDVI", "Write", "Zonal")
ggplot(df_agg, aes(x = task, y = time)) +
  geom_point(aes(shape = lang, color = package), size = 2, alpha = 0.8,
             position = position_jitter(width = 0.2, seed = 1)) +
  labs(title = "Benchmark raster operations", color = "Package",
       shape = "Language") +
  scale_x_discrete(labels = xlabels) +
  scale_color_brewer(palette = "Set1") +
  ylab("Time [s]") +
  xlab("Task") +
  theme_light() +
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
timings = aggregate(time ~ task + package, df, median)
colnames(timings)[3] = "median"
timings$median = round(timings$median, 2)
write.csv(timings, "timings.csv", row.names = FALSE, quote = FALSE)
```

